# Generated by Django 3.2.3 on 2021-05-27 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogapp', '0002_auto_20210527_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('approved', models.BooleanField(default=False)),
                ('approved_time', models.DateTimeField(auto_now=True, null=True)),
                ('uploaded_time', models.DateTimeField()),
                ('description', models.CharField(max_length=500, null=True)),
                ('keyword', models.CharField(max_length=500, null=True)),
                ('image_id', models.CharField(blank=True, max_length=300, null=True)),
                ('Certified', models.BooleanField(default=False)),
                ('approved_by', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
