# Generated by Django 3.2.3 on 2021-05-28 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_auto_20210528_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='fb_url',
        ),
        migrations.RemoveField(
            model_name='author',
            name='ld_rul',
        ),
        migrations.RemoveField(
            model_name='author',
            name='tw_rul',
        ),
    ]
